name: Publish core-sdk package
on:
  workflow_dispatch
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          scope: <REDACTED>
      - name: install root deps
        run: yarn install
      - name: install dependencies
        run: yarn install
        working-directory: ./packages/core-sdk
      - name: publish package
        run: yarn publish
        working-directory: ./packages/core-sdk
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
